### ISSUE TITLE
Installation Error on pi4

### ISSUE THREAD

**Issue by lupos** [DrAlexLiu/OctoPrint-PiNozCam#15]
First of thanks for making this! Very excited to try it out. I generally don't love opening issues but I did google as much as I could and can't really find anything about this error. Also python is very much not my wheel house or I would try and dig in further. 

Anyway I am trying to install it via the plugin manager and getting the following error on a pi4

> `Installing plugin "OctoPrint-PiNozCam" from https://github.com/DrAlexLiu/OctoPrint-PiNozCam/archive/master.zip...
> /home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install file:///tmp/tmpt9vqio7l/OctoPrint-PiNozCam-master.zip --no-cache-dir
>
> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
> Processing /tmp/tmpt9vqio7l/OctoPrint-PiNozCam-master.zip
>
> ERROR: onnxruntime-1.16.0-cp39-cp39-linux_armv7l.whl is not a supported wheel on this platform.
>
> Error!
> Could not parse output from pip, see plugin_pluginmanager_console.log for generated output`

**Comment by DrAlexLiu** [comment]
are you using Buster or Bookworm 32bit version?

follow here and check your system OS platform:
https://raspberrytips.com/which-raspberry-pi-os-is-running/

**Comment by DrAlexLiu** [comment]
@lupos 
I have a solution for the Bookworm 32bit.

Also, may I know your environment?
Python version?
OS version?
OS 32 or 64bit?

**Comment by DrAlexLiu** [comment]
I have released a new version v1.0.1 and it should support all RPi OS (both x32 and x64). If you encounter a new issue, please let me know.
