### ISSUE TITLE
Feature request: max failure messages per print

### ISSUE THREAD

**Issue by jofland** [DrAlexLiu/OctoPrint-PiNozCam#18]
When a failure is detected I get Telegram messages until the print is stopped. Then my phone gets crazy :-).

I would like to request a limit input field for failure messages per print. E. g. setting this to "5" would only send max. 5 messages within one print job.

There should be a option to switch the limit off. Could be reached by "0" as input value.

**Comment by DrAlexLiu** [comment]
Sure. I will do it.

**Comment by DrAlexLiu** [comment]
@jofland 
I really want to get a telegram/discord two-way communication. Like, when sending a failure picture, it will have three options:
mute, pause, and stop. 

When you click one of three buttons, like mute, you won't receive any more notifications. (It could also be false alarms, keeping sending error printing while it is printing good.)

when you click pause or stop, you can stop the failure print even if you are outside your home, etc. 

However, this design requires async/await functions, which is conflict with octoprint's flask service. I am trying to how to solve it. 

But I will do your request first.

**Comment by DrAlexLiu** [comment]
@jofland 
I really want to get a telegram/discord two-way communication. Like, when sending a failure picture, it will have three options:
mute, pause, and stop. 

When you click one of three buttons, like mute, you won't receive any more notifications. (It could also be false alarms, keeping sending error printing while it is printing good.)

when you click pause or stop, you can stop the failure print even if you are outside your home, etc. 

However, such this design requires async/await functions, which is conflict with octoprint's flask service. I am trying to how to solve it.

**Comment by DrAlexLiu** [comment]
@jofland 

Would you please try this test.zip? 

https://github.com/DrAlexLiu/OctoPrint-PiNozCam/archive/test.zip

To test, an easy way is to:
Put
https://raw.githubusercontent.com/DrAlexLiu/OctoPrint-PiNozCam/master/assets/images/failure_detection2.jpg
in the custom URL, and set the printer to a virtual printer,

Let me whether you need to other modifications?

One more thing:
When you are printing and turn AI from OFF to ON, your printer will experience a pause/blob. I can get this away, but it will load the AI model into memory even switch is set to OFF (It should not be designed in this way).

**Comment by jofland** [comment]
> Would you please try this test.zip?

Sorry, the test failed. Here what I did:

Custom URL as you said.

Test 1:
- Max Notification Count = 0
- Got continuing failure messages after each some seconds
==> Test for deactivation OK

Test 2:
- Max Notification Count = 5
- Got no failure messages at all
==> Test failed

Test 3:
- same as test 2 with Max Notification Count = 2


> Let me whether you need to other modifications?

Next improvement could be mouse over hints for the input fields :-)


> One more thing: When you are printing and turn AI from OFF to ON, your printer will experience a pause/blob. I can get this away, but it will load the AI model into memory even switch is set to OFF (It should not be designed in this way).

I did not understand what you mean by this? Do you mean this could cause a problem with IO traffic to my ssd (related to the other issue last week)?

**Comment by DrAlexLiu** [comment]
Thanks. 

For the situations like test2 and test3, it was working on my end last night. I will take a look again tonight. 

I did not understand what you mean by this? Do you mean this could cause a problem with IO traffic to my ssd (related to the other issue last week)?

Sort of. So:
1. When you are printing a job, and you turn on the "Enable PiNozCAM" from OFF to ON, and click save. it will load the AI model data from SSD and it will cause a pause/blob only happens one time. 

2. If you turn on/off the "Enable PiNozCAM" and click save when you are not printing, or you turn "Enable PiNozCAM" to OFF while you are printing, it would not cause a pause/blob.

**Comment by jofland** [comment]
> For the situations like test2 and test3, it was working on my end last night. I will take a look again tonight.

I just realized I did all tests within the same print job and got more than 5 failure messages in test 1. So there shouldn't have been any messages in test 2 and 3. Version might be working.

I will run an isolated test 2 in a fresh print job.

**Comment by jofland** [comment]
I tested again. It´s working, but there is an **off by one**:

Test 4:
- Max Notification Count = 4
- started a new print job
- got exactly 3 failure messages
- stopped the print job

Test 5:
- Max Notification Count = 3
- started a new print job
- got exactly 2 failure messages
- stopped the print job

Test 6:
- Max Notification Count = 2
- started a new print job
- got exactly 1 failure message
- stopped the print job

Test 7:
- Max Notification Count = 0
- started a new print job
- got continuing 6 failure messages and canceled the print job

**Comment by DrAlexLiu** [comment]
@jofland 

Thank you for testing. I have updated it and would you download and try the test.zip again?

Next improvement could be mouse over hints for the input fields :-)
I try to add the responsive UI like this, or use a similar way to explain the parameters in a detailed way.

**Comment by jofland** [comment]
Testresults (Tests as above):

Test 4:
- Count=4
- 4 failure messages
- OK

Test 6:
- Count=2
- 2 failure messages
- OK

Test 7:
- Count=0
- 6 failure messages, then canceled
- OK

**Comment by DrAlexLiu** [comment]
@jofland 

Thank you for your detailed testing. I have already fixed the bug. It should solve the issue you mentioned.

**Comment by jofland** [comment]
Test is OK :-)

**Comment by DrAlexLiu** [comment]
@jofland 

When a failure is detected I get Telegram messages until the print is stopped. Then my phone gets crazy :-).

A: The version 1.0.3 has a remote control on Telegram. You can remote stop it, or at least mute it. I hope this function will help you.
