### ISSUE TITLE
Feature request: delay in starting detection and crop camera image

### ISSUE THREAD

**Issue by giovi321** [DrAlexLiu/OctoPrint-PiNozCam#25]
I have a problem: the camera  is a wide lens, so it sees a little bit also outside the printing bed when it is in the home position and detects some wires as a printing failure.
I see two options:

1. Add a delay before starting to detect failures, so that when i start the print PiNozCam waits 20 seconds for the bed to be centered
2. Crop the image of the camera to a region

**Comment by DrAlexLiu** [comment]
Sure. I will add delay and mask on the camera.

**Comment by DrAlexLiu** [comment]
@giovi321 

Thank you for using this plugin. I'm sorry for getting back to you so late. Finally, I have fulfilled your request. 

Please use this branch to test, and let me know if you have any feedback. 
[](https://github.com/DrAlexLiu/OctoPrint-PiNozCam/archive/test.zip)

**Comment by giovi321** [comment]
Thank you so much!

**Comment by DrAlexLiu** [comment]
@giovi321 

May I ask how is your test going? This weekend, I will merge the test branch into the main branch. If everything good, I will release the 1.0.2.

I welcome any feedback. Also, welcome to join the discord.

**Comment by DrAlexLiu** [comment]
Release v1.0.2 to support your request. 

Use this.
https://github.com/DrAlexLiu/OctoPrint-PiNozCam/archive/master.zip
