### ISSUE TITLE
installed but not showing or working

### ISSUE THREAD

**Issue by montyfert** [DrAlexLiu/OctoPrint-PiNozCam#32]
hi i installe it using octoprint plugin manager but it does not show in plugins so cant remove it . 
how do i remove it.
thanks 
martin

**Comment by DrAlexLiu** [comment]
pip uninstall OctoPrint-PiNozCam. 

Also, you can uninstall it from OctoPrint plugin Manager.

**Comment by montyfert** [comment]
thank you , 
it was not showing in octoprint plugin manager.
martin
