### ISSUE TITLE
Install Not Getting Requirements

### ISSUE THREAD

**Issue by jneilliii** [DrAlexLiu/OctoPrint-PiNozCam#7]
There have been multiple reports on Discord and in the forum of people installing this plugin and it not loading properly because it's missing dependencies. Here's one example.

https://community.octoprint.org/t/pinozcam-plugin-unable-to-show-up/57331

I suspect it's from your conditional setup_requires possibly?

**Comment by DrAlexLiu** [comment]
In setup.py

I change the method to determinate the x32 or x64 platform. Now using
import struct

it can identify the python's architecture, instead of CPU's architecture. It should be more accurate.

**Comment by jneilliii** [comment]
make sure you create a release that matches the version number in setup.py. that's how software update checks will get updates.

**Comment by DrAlexLiu** [comment]
Create first release v1.0.0
